### ISSUE TITLE
auto build custom blender

### ISSUE THREAD

**Issue by hartsantler** [MARUI-PlugIn/BlenderXR#1]
the `blender` folder contains many files that replace parts of blender2.8 source code; while it is easy enough to copy these over to my blender2.8 source, and rebuild.  it would still be nice if the main cmake file would automatically git clone the latest blender2.8 source, do the copy and then rebuild blender for me.

**Comment by max-krichenbauer** [comment]
Thank you for the comment!
This current way of providing the source code is only a temporary solution.
In the long run, we hope that our code changes get accepted into the Blender code base.
We only opened this repository because people asked us about a beta version.
You can get pre-built binaries at https://www.marui-plugin.com/blender-xr/

**Comment by dfelinto** [comment]
What I would suggest (even temporarily) is to use git submodule to store the blender code, and to keep your version of blender as a branch in your github as well.

This way it should be really straightforward to manage both repositories separately, keeping the blender changes easily diffable against a known branch (said blender repository could strictly have only blender2.8 and the blenderxr branches).

Also you may want to consider git lfs for the binaries. Specially if you plan to update them semi-regularly. (and if you need any help setting either of those up I can gladly help).

**Comment by pk15950** [comment]
Hi all, I updated the git to store the binaries with git lfs. I also set up a separate branch to "track" the latest blender2.8.

@hartsantler I'm having some issues setting up the git properly to do the "auto pull, patch, and build." If you want, I'd really appreciate it if you could look into it. I also adapted your python script for the current repository structure, although it needs fixing.

[update_build.txt](https://github.com/MARUI-PlugIn/BlenderXR/files/2477711/update_build.txt)

**Comment by hartsantler** [comment]
i wish i had more time to update my build script to the new structure, hopefully i will later.  for now my build script is working, and i have to go with it for now.
where do i copy `libBlenderXR_SteamVR.so`  and `libopenvr_api.so` to when i have built everything?

**Comment by pk15950** [comment]
Ok, well if it works for you then that's great. 
The .so files should go in the build output directory (where the Blender executable is) but actually at the moment you still need to set the environment variable LD_LIBRARY_PATH to the output directory (or alternatively have the libraries somewhere on your path) so that the libraries get loaded. 
I will work on refactoring this as soon as possible.

**Comment by pk15950** [comment]
The .so files are now loaded from the executable directory without the need to set LD_LIBRARY_PATH.
