### ISSUE TITLE
Suggestions + bugs I found

### ISSUE THREAD

**Issue by ghost** [MARUI-PlugIn/BlenderXR#12]
I am thrilled someone has taken on the challenge of adding support for VR in blender! I am testing it out right now with the HTC Vive and it is awesome. Thank you for your time and for making this plugin free.

Right away I saw a few things that could be done to improve this tool. I am only posting because I believe this is the future and I wanted to contribute my part to make sure that this tool is the very best it can be.

**In short:**
1. Make it to where I can see the mouse in VR
2. Create blender XR to support multiple tools 
3. Add Vive Tracker Support as an additional tool to the controllers
4. Add Mouse/Keyboard functionality so that I can use it along side the controllers while building things. This will allow for much more complex configuration and usefulness for the Blender XR Tool

**Suggestions:**
Add support to integrate mouse and keyboard inside VR. If I could see my mouse inside the headset, I would be able to build models with the headset much easier. It would be great if I could sit at my computer and build stuff with the headset on and just use the mouse/keyboard. If you haven't tried an app that supports this yet, it is actually incredible useful and feels natural to use to mouse and keyboard. I just know that blender is a very complex tool and while the controllers lack buttons/functionality for some of blenders features, the mouse with the headset would work perfectly. What would be awesome is if I could use the controllers and mouse side by side. So I could make some adjustments, then pick up my controllers and use it for something else. 

**Vive Tracker support**
Support for Vive trackers in Blender XR. You may already have support, but it would be cool if I could use and implement the vive tracker as an additional tool to the controllers and potentially the mouse.

**Issues:** 
Using the mouse and adding a cube causes the app to crash. This ties in with implementing mouse/keyboard functionality along side the controller. This would be a major step in the right direction if you could fix this bug. Every time I try to add an object with the mouse inside the new VR window it just crashes.

**Comment by pk15950** [comment]
Hi winsteadworks,

Thank you very much for your feedback. We're happy to hear that you're enjoying BlenderXR and we appreciate your suggestions.

"2. Create BlenderXR to support multiple tools"
We are actively working on adding more tools to BlenderXR but please understand that this will take some time as many of the existing Blender tools must be specifically adapted to VR on a case-by-case basis. 

"3. Add Vive Tracker Support as an additional tool to the controllers"
Vive tracker support is actually available in BlenderXR and if you connect a Vive tracker, it will read the tracking data. However, since we haven't implemented any relevant features, there is no way for the user to see this data and the tracker will not even be rendered. 
In what way would you like to use the Vive tracker? If you can give us an example use case then we can work on implementing it.    

"1. Make it to where I can see the mouse in VR "
"4. Add Mouse/Keyboard functionality"
Adding mouse and keyboard functionality would be possible, however at the moment we are focusing more on developing the user interface for the VR controllers. 
Since the VR window that pops up is in fact a Blender window, you probably know that if the window is active you can use your mouse and keyboard, although you can't see the mouse cursor. We can add rendering for the mouse cursor but anything more than that will probably not be worked on in the near future.

Thanks for reporting the bug, we'll work on fixing it immediately.

**Comment by pk15950** [comment]
Hi winsteadworks,

I believe I fixed the issue causing crashes when adding new objects from the VR window. I also added basic mouse cursor rendering so you can see and accurately use the mouse in VR. 

To toggle the mouse cursor visibility (off by default), switch to the "Select" widget on one of your controllers and hold down the trigger. Then, you should see a cursor icon in the center of the touchpad appear. You can then press down on the touchpad to toggle the mouse cursor rendering. 

I apologize that the toggle is in such a strange location but this will be refactored and moved to a better place in the future. You may also notice that the mouse cursor is only rendered to one eye. This is intentional in order to accurately match the 2d screen coordinates of the actual cursor and at the moment I have not found a good method to render it to both eyes. Hopefully this can be improved in the future, but for now I hope that you find this feature useful for your work.

Both the git repository and the precompiled binaries on the MARUI-PlugIn website: https://www.marui-plugin.com/blender-xr/ have been updated.

**Comment by ghost** [comment]
Great! I am going to download the update and try it out right now. I really appreciate the quick and thorough responses, I really believe this is going to be a huge success. Keep up the good work and it will pay off big time! 

I think it will be really beneficial to allow using the mouse and keyboard to build, because you can't do everything on controllers yet and due to limited functionality it will be really helpful to be able to use blender to its full capacity still while in VR.

Are there any plans to allow extruding and cuts in the near future? Also what about reshaping objects?

**Comment by winsteadworks** [comment]
Would there be and way that I could toggle the menu and what not to be visible in blender too so that I can build and edit completely in while in vr?

**Comment by winsteadworks** [comment]
When I say menu I am referring to the rest of the blender gui for adding and building stuff that is not visible in vr window. Also this would be a great opportunity for adding more buttons. If you could make the menu pop up with all of the gui you would open up the possibility of full access to vr editing in blender. While you might not be able  to do all of them with the vive controllers for instance just yet, you could atleast use your mouse and keyboard. Also If you did add the menu you could potentially add a feature where your controllers are a laser pointer and you could click the button with your vive controller that way. This could work just like your mouse does and just make the trigger button be the equivalent of a left click. This could be a great opportunity for your team because instead of trying to fit all of the buttons on the controller, you could take advantage of what is already built and just point to click your tool. It seems blender 2.8 was built with vr in mind already. I could see you all taking this menu concept a long way if implemented correctly.

**Comment by winsteadworks** [comment]
![blender](https://user-images.githubusercontent.com/38088621/50054468-ad92f900-0107-11e9-9ad0-a8862498cab9.PNG)

Basically what I am saying is make it to where you can see all of this inside vr as a toggle feature too. Even if I can't click the interface yet with the laser point idea via vive controllers just yet, you could still at least use your mouse and this would enable the possibility of full featured vr editing with just a small update

**Comment by winsteadworks** [comment]
Yea if you could essentially allow a toggle where you vr controller IS the mouse in your blender screen itself (sort of like how if you view desktop and control it through vr in steam) this could be huge. If you added the menu and allowed a toggle to turn your controller into the mouse itself and behave like it, then you could control all of the menu items thus enabling full vr editing support overnight, plus the ability to move the mouse in 3 dimensions, where you are limited to your view of where the mouse actually is currently when viewing threw the vive headset

**Comment by winsteadworks** [comment]
![blender2](https://user-images.githubusercontent.com/38088621/50054598-378f9180-0109-11e9-8f51-fa31219d289f.PNG)
Here is an example of this being super useful, I could have my headset on, go to the sculpting tab, and inside the headset I can see the menu too, so I can go over to the left of the screen, select my tool, and then start sculpting all while still inside the headset. That way I don't have keep taking my headset on and off to build stuff in blender

**Comment by winsteadworks** [comment]
By the way when I am switching tabs in vr mode (sculpting to modeling or layout or any tab for that matter) there is a bug where blender will crash when I am switching through these tabs

@pk15950

**Comment by winsteadworks** [comment]
![b3](https://user-images.githubusercontent.com/38088621/50054691-14191680-010a-11e9-8e70-f93d4b49147c.PNG)
Also if I could see these menus in vr window inside my vive, this would be a game changer too. Like I said you can implement the laser click function with the vive and other vr headset controllers to take full control of this. Keyboard + mouse + vive controller actually work really well together. Since there are so many buttons in blender, it is almost necessary to consider combination of mouse and keyboard with the vive controller for now to make full vr editing possible and to make this tool more than just a demo but truly useful for building and designing. The great thing is you are already so close, I think a few minor tweaks and adding the menu will make this plugin allow true vr editing.

Even if you don't add the laser controller pointer function yet, just making it possible to toggle so that it is visible inside the headset would be a game changer, because I can see and use my mouse now so I would be able to work completely uninterrupted with my headset on the entire time

**Comment by ghost** [comment]
Would there be and way that I could toggle the menu and what not to be visible in blender too so that I can build and edit completely in while in vr?

When I say menu I am referring to the rest of the blender gui for adding and building stuff that is not visible in vr window. Also this would be a great opportunity for adding more buttons. If you could make the menu pop up with all of the gui you would open up the possibility of full access to vr editing in blender. While you might not be able to do all of them with the vive controllers for instance just yet, you could atleast use your mouse and keyboard. Also If you did add the menu you could potentially add a feature where your controllers are a laser pointer and you could click the button with your vive controller that way. This could work just like your mouse does and just make the trigger button be the equivalent of a left click. This could be a great opportunity for your team because instead of trying to fit all of the buttons on the controller, you could take advantage of what is already built and just point to click your tool. It seems blender 2.8 was built with vr in mind already. I could see you all taking this menu concept a long way if implemented correctly. 

Basically what I am saying is make it to where you can see all of this inside vr as a toggle feature too. Even if I can't click the interface yet with the laser point idea via vive controllers just yet, you could still at least use your mouse and this would enable the possibility of full featured vr editing with just a small update

![blender](https://user-images.githubusercontent.com/38088621/50054847-12505280-010c-11e9-93dd-f47336e1e333.PNG)


Also the mouse update is great and I am no longer crashing, thanks for the fix!

Yea if you could essentially allow a toggle where your vr controller IS the mouse in your blender screen itself (sort of like how if you view desktop and control it through vr in steam) this could be huge. If you added the menu and allowed a toggle to turn your controller into the mouse itself and behave like it, then you could control all of the menu items thus enabling full vr editing support overnight, plus the ability to move the mouse in 3 dimensions, where you are limited to your view of where the mouse actually is currently when viewing threw the vive headset.

Here is an example of this being super useful, I could have my headset on, go to the sculpting tab, and inside the headset I can see the menu too, so I can go over to the left of the screen, select my tool, and then start sculpting all while still inside the headset. That way I don't have keep taking my headset on and off to build stuff in blender.
![blender2](https://user-images.githubusercontent.com/38088621/50054840-f8167480-010b-11e9-968b-5d8768e67c88.PNG)

By the way when I am switching tabs in vr mode (sculpting to modeling or layout or any tab for that matter) there is a bug where blender will crash when I am switching through these tabs

![b3](https://user-images.githubusercontent.com/38088621/50054835-e3d27780-010b-11e9-9920-88bf761e5b58.PNG)

Also if I could see these menus in vr window inside my vive, this would be a game changer too. Like I said you can implement the laser click function with the vive and other vr headset controllers to take full control of this. Keyboard + mouse + vive controller actually work really well together. Since there are so many buttons in blender, it is almost necessary to consider combination of mouse and keyboard with the vive controller for now to make full vr editing possible and to make this tool more than just a demo but truly useful for building and designing. The great thing is you are already so close, I think a few minor tweaks and adding the menu will make this plugin allow true vr editing.

Even if you don't add the laser controller pointer function yet, just making it possible to toggle so that it is visible inside the headset would be a game changer, because I can see and use my mouse now so I would be able to work completely uninterrupted with my headset on the entire time

Good news is you really don't need to do anything to make the keyboard and mouse fully functional now besides editing the ability to see the menus and buttons inside the headset

One more thing it would be great if when I rotate the view with my mouse, it rotated my view in my virtual reality headset. Would be great for if I am working in my headset but just with mouse and keyboard at the moment and that way I don't have to pick up my controller every time I want to rotate my view

**Comment by ghost** [comment]
One possible alternative to the mouse solution is adding a toggle button to the mouse by moving your thumb on the touchpad on the vive controller and a button to click so you and use the menu and tools with your vive controller

**Comment by mkdior** [comment]
Hi Winsteadworks,

First off, sorry for the late reply! We’re all working hard on squashing bugs and implementing new features! Before starting off replying to your suggestions and bug reports, I’d like to first talk about the current differences between Blender and BlenderXR.

Blender itself is a great piece of software, with many well constructed ideas which could all very well work in VR too. The big obstacle we're facing now is pure, early development. We understand that the folks over at Blender have worked hard on coming up with an intuitive user interface design which we all have come to appreciate! The problem as you might have noticed is the fact that said user interface was designed with the mouse and keyboard in mind. Due to BlenderXR still being in early development, it is critical for us to start off with a solid VR user interface before we delve any deeper into integrating the existing user interface into the BlenderXR window. We understand that it's something many people long for and something that's useful in general. 

With respect to rendering the menus in VR, it would be possible, however, at the moment it would require too much overhead. Specifically, in Blender, menus are drawn separately from the viewports and as the VR eye textures are linked exclusively to the viewports, drawing the menus would require adding additional VR textures for the menus, thus doubling the amount of rendering work.
One of our core concerns is workflow. To be more specifically, efficient workflow. We feel that that current, critical features which Blender offers should also be made available in BlenderXR, separate from Blender's core user interface. This because it allows users to work fast and efficiently without being blocked by the necessity of having to laser point their way to the features they need. Don't get me wrong, your suggestions sound very alike to Oculus' desktop; which is very useful! The thing is, however, we're focusing our development effort on those key features. Integrating Blender's user interface into BlenderXR while working on the other features is unrealistic as of now in terms of our development resources.

What I'm trying to say is that before we delve into fully integrating mouse and keyboard functionality( and of course Blender's UI.), we first want to have the core features available in BlenderXR. With these core features also comes a fully fledged, virtual reality user interface. Which is not only easy to use, but allows the Blender user to be as efficient in BlenderXR as in Blender. 

To quickly summarize the suggestions and bug reports you listed in your posts; 

**Laser pointer feature**: Since rendering menus isn't on our current list of "to implement" features, this won't be necessary unless we implement a desktop/ hybrid app feature.

**Tab switching**: This really shouldn't be happening! We'll be on it right away!

**Rotating BlenderXR's view based on Blender's view**: Any mouse viewport controls will not ( and should not, at least at the moment ) change the VR view. This is because the VR view is tied to the VR navigation matrix that holds all the information of where the user is relative to the scene. In order to allow for, say, mouse rotation, we would need to catch every single viewport rotation event and adjust our navigation matrix accordingly. As it is, the viewport rotation is simply ignored since the VR view is set every single frame based on the navigation matrix.

Thank you so much for your bug reports and suggestions! We appreciate it!

**Comment by Defaultsound** [comment]
Just want to add to the discussion. 

Having support for Vive trackers would be super useful for animation. In theory you could parent the trackers location to a bone in an armature for example, then record the animation. This would act as a neat motion capture system. I know there is paid software out there that does this, but to include it into this plugin could be really good.

**Comment by ghost** [comment]
Thanks for adding on to this. I definitely agree that trackers would be
great for animation
