### ISSUE TITLE
UI isn't usable

### ISSUE THREAD

**Issue by riccardogiorato** [MARUI-PlugIn/BlenderXR#14]
The UI with the oculus rift on the controllers is impossible to use.

![image](https://user-images.githubusercontent.com/4527364/50536011-366e5380-0b50-11e9-9d0e-c93e885ca9b2.png)

Looking at this there are too many layers of text all on top of each other.

Have you considered easier and larger menu with easy selection like in Google blocks like this?
![image](https://user-images.githubusercontent.com/4527364/50536032-759ca480-0b50-11e9-9ba0-0d52fafab6b9.png)

**Comment by mkdior** [comment]
Hi Giorat,

I'm sorry to hear that you're experiencing issues using the current BlenderXR UI. I'd like to stress the fact that BlenderXR is still _**very**_ early in development. With each update we strive to improve functionality and user experience. With that of course comes the UI. The UI that's implemented as of now should give you a rough idea of what we're aiming for. We're trying to be consistent with Blender's UI; the pie menus specifically. Since this is what we're striving for; the menu shown in the second screenshot would feel very out of place in Blender.

The screenshot you have listed of the current UI is in terms of development already outdated. We've replaced the pieces of text with actual icons. Pretty much most icons have been updated and scaled down which allows for more "breathability" on the VR controllers. 

Since we're rapidly adding functionalities to BlenderXR, it means that sometimes we have to add placeholders to the menus to allow Blender users to test said functionalities out without having to wait for us to implement new UI designs. I hope that this clears up the issues you're currently facing with the current UI design.

Kind Regards,

Meuko

**Comment by riccardogiorato** [comment]
Are the icons available how? I installed the blender XR version from your website, should I use the one here on github to get the latest version updates?

**Comment by mkdior** [comment]
Hi Giorat,

We will be releasing an update somewhere in the next few weeks. This update will contain the new icons. I hope that clears up some things!

Kind regards,

Meuko

**Comment by guiglass** [comment]
Hi, this is very neat, but I also can not use the UI.

I keep wanting to treat it as a HMD gaze pointer to select menu items but then remember I have to rotate my thumb around touchpad (which is not intuitive, especially with Knuckles).

Would it be possible to integrate gaze pointer mode?

**Comment by pk15950** [comment]
Hi guiglass,
It would be possible to integrate gaze pointer mode, however at the moment we are focusing on adding more edit mode features so it may be some time before this is implemented.

Unfortunately we don't have access to the Knuckles controllers, but it's likely that the UI will be modified once we're able to test with these devices.    

That being said, if you (or anyone else) would like to take on the task of developing an alternative UI, any contributions would be more than welcome.
