### ISSUE TITLE
Using BlenderXR with regular monitor

### ISSUE THREAD

**Issue by ariadesu** [MARUI-PlugIn/BlenderXR#18]
Please consider the possibility of using the VR input method without a HMD. The blender viewport updates much faster than the VR window, and the fidelity will also be better for most users. Obviously VR has huge advantages for conveying scale, but pancake is good too. 

I would like to move, clone and rotate objects with the ease and precision I can with Oculus Touch, just behind my desk. Will you be able to support this? 

Ps. you will need to keep the headset alive in the case of Oculus to read controller input.

**Comment by pk15950** [comment]
Hi ariadesu,
Thanks for your feedback. Yes, I believe this would be possible.

Since the repository/binaries will probably not be updated for another week, in the meantime, if you can build from source, you can use this patch. 

Let me know if this isn't what you had in mind.

[no_hmd_patch.txt](https://github.com/MARUI-PlugIn/BlenderXR/files/2847424/no_hmd_patch.txt)
![no_hmd_patch](https://user-images.githubusercontent.com/23358587/52515219-2459f780-2c5c-11e9-8888-cf06acda7f57.png)

**Comment by ariadesu** [comment]
That is great! I will attempt to build and try it right away and give feedback. Thank you very much!
