### ISSUE TITLE
GPL violation

### ISSUE THREAD

**Issue by iRi-E** [MARUI-PlugIn/BlenderXR#6]
All of Oculus SDK, OpenVR, and FoveSDK are proprietary softwares that's incompatible with GPL, so you must not use them for supporting VR HMDs and have to use open sourced VR SDK such as OSVR and OpenHMD instead.

https://developer.blender.org/T47899
https://www.gnu.org/licenses/license-list.html.en#OculusRift
https://forums.oculusvr.com/developer/discussion/487/rift-sdk-and-gpl
https://github.com/ValveSoftware/openvr/issues/8

**Comment by max-krichenbauer** [comment]
Thank you for your message.
There seems to be a misunderstanding:

BlenderXR is an abstraction layer that builds dynamic libraries.
It is completely separate from Blender.

The Blender version in this repository does not link against any proprietary libraries nor does it include any code from OculusSDK, OpenVR, or FoveSDK.
It merely adds the option to use BlenderXR (the abstraction layer) which is not a GLP violation. (If it were, any use of any Windows function in the Blender source code would be so as well, since Windows is proprietary).

We have chosen this approach precisely to avoid any licensing problems.
People are free to use, copy, and change our modified version of the Blender source code. The GPL applies. There is no non-GPL code in our modified version of the Blender source code.

It is only for convenience that we host our modified version of Blender in this repository together with BlenderXR. We could also upload it as a .zip file on our website, but feel that this way is more convenient and transparent.

Sorry for the confusion. We'll clarify this point in the readme.

**Comment by iRi-E** [comment]
I think you have to read FAQ about GPL carefully.

https://www.gnu.org/licenses/gpl-faq.html.en

Dynamic inking  does't separate the program. It merely makes one combined program and the GPL applied to the whole of progam including dynamically linked module.
If you'd like to make separated programs, the abstraction layer must be running as a separate process and communicate with Blender via IPC such as pipe and socket using generalized protocol.

> any use of any Windows function in the Blender source code would be so as well, since Windows is proprietary

VC++ runtime is a system library that the "system library exception" is applied to.
VR runtime is obviously not a system library so the exception is not applied.

**Comment by dfelinto** [comment]
Regardless of the specifics of licensing, this discussion will be irrelevant once [OpenXR](https://www.khronos.org/openxr) is out and used as a backend (assuming this is part of the plans here).

They are not selling the plugin, they are really opening all the sources. If the .dll they were linking to was their proprietary solution, it would be different. It is not the case though, and from what I see this falls into a grey area, that could be engineered away if must be. Blender itself does dynamic loading of non-open libraries (e.g., decklink in Blender 2.7x).

**Comment by max-krichenbauer** [comment]
@iRi-E 
Thank you again for your comment and sorry for the complicated situation.
As far as we understand, it is not a GPL violation for GPL software to use non-free libraries given that:
- a permission is given / the license text section 7 is updated
- removing the dependency is planned in the future
https://www.gnu.org/licenses/gpl-faq.html#FSWithNFLibs
https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs

In the case of this repository:
(1) The Blender source code in the folder /blender/ remains GPL v3
(2) the altered Blender source code *can* (not must) utilize the presence of BlenderXR libraries
(3) BlenderXR is GPL v3 open source software with special permission (section 7)
(4) LibOVR, OpenVR, FoveSDK and GLEW remain their respective licenses and are redistributed in unaltered form here only for convenience. (Redistribution is allowed under each respective license)
(5) BlenderXR is only a temporary work-around until OpenXR will become available. Then the BlenderXR library will be discontinued and our version of Blender will use OpenXR directly.

If you are not satisfied with that, could you please explain your relation with the licensing issue?
Do you represent the copyrights holder of any of the code or libraries included in this repository (Blender, OpenVR, FoveSDK, LibOVR or GLEW)?
We are happy to cooperate if you feel that your rights have been violated, but unless you are a copyright holder you cannot request us to make changes to BlenderXR to remove the dependencies.

**Comment by max-krichenbauer** [comment]
@dfelinto 
Thank you very much for your comment!
That is indeed the case: BlenderXR is only a temporary work-around and will be discontinued as soon as OpenXR becomes available.

**Comment by mdovgialo** [comment]
>VR runtime is obviously not a system library so the exception is not applied.

Why? It is a driver for a type of monitor communicating through standardised open source openvr header/library using IPCs.

Drivers are not system libraries?
