### ISSUE TITLE
When changing lookdev rotation, it only works for the left eye

### ISSUE THREAD

**Issue by dfelinto** [MARUI-PlugIn/BlenderXR#7]
How to reproduce:
* Default scene with default cube
* Open the BlenderXR new window
* Change shading mode to lookdev
* Pick the studio.exr HDRI (the problem is there with others, but it is easier to see with this one)
* Change the HDRI rotation (e.g., 25°)

The left eye updates accordingly, while the right eye is stuck with the previous shading effect.

**Comment by pk15950** [comment]
Hi dfelinto,
Thanks for your feedback! The issue came from an EEVEE lighting optimization where the second (right) eye was not updated because the lighting was assumed to have already been calculated/applied. 

The issue should be fixed now and the compiled binaries on the MARUI-PlugIn website have been updated accordingly.
